 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';
var fs = require('fs');
var express = require('express');
var app = express();
var routes = require('./app/routes/index.js');


var port = process.env.PORT || 8080;

// The format follows as, alias to use for real path, also allows permission to such path.
//app.use('/api', express.static(process.cwd() + '/app/api'));

routes(app);

app.listen(port, function() {
    console.log('Node.js listening on port ' + port);
});